apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: sidecar
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: client
    name: test-example-app
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      deploymentconfig: test-example-app
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: client
          deploymentconfig: test-example-app
      spec:
        containers:
        - env:
          - name: PERIOD_SECONDS
            value: "10"
          - name: OPTIONS
            value: -V -k example@EXAMPLE.COM
          image: edseymour/kinit-sidecar@sha256:3cd0c9aeb8fc3d51a75bd057565b369bf4f1d09d9d10f7fcbd98462cafba1131
          imagePullPolicy: Always
          name: kinit-sidecar
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /krb5
            name: keytabs
          - mountPath: /dev/shm
            name: ccache
          - mountPath: /etc/krb5.conf.d
            name: config
        - command:
          - /bin/sh
          - -c
          - while true; do echo "*** checking if authenticated"; klist ; sleep 5;
            done
          image: edseymour/kinit-sidecar@sha256:3cd0c9aeb8fc3d51a75bd057565b369bf4f1d09d9d10f7fcbd98462cafba1131
          imagePullPolicy: Always
          name: example-app
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /dev/shm
            name: ccache
          - mountPath: /etc/krb5.conf.d
            name: config
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: keytabs
        - emptyDir:
            medium: Memory
          name: ccache
        - configMap:
            defaultMode: 420
            name: test-krb5-client
          name: config
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - example-app
        - kinit-sidecar
        from:
          kind: ImageStreamTag
          name: test-kinit-sidecar:latest
          namespace: krb-ex-wv6c
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
